##################################################################################################
# Service section
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.deployment.container.namespace }}
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Chart.Name }}
spec:
  ports:
  - port: 90
    targetPort: 8080
    name: http
  selector:
    app: {{ .Chart.Name }}
---
##################################################################################################
## Deployment section                                                                            ##
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.deployment.container.namespace }}
  annotations:
    configmap.reloader.stakater.com/reload: "mx-istio-demo-configmap-base,{{ .Chart.Name }}-config"
  labels:
    app: {{ .Chart.Name }}
    release: stable
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: live
    spec:
      securityContext:
        runAsUser: 2000
        fsGroup: 2000
      containers:
        {{- with .Values.deployment.container }}
        - name: {{ .name }}
          imagePullPolicy: Always
          image: {{ .repository }}{{ .image }}-{{ .namespace }}:{{ .tag }}
          resources:
            requests:
              cpu: {{ .cpuReq }}m
              memory: {{ .memReq }}Mi
            limits:
              cpu: {{ .cpuLim }}m
              memory: {{ .memLim }}Mi
          ports:
            - containerPort: {{ .containerPort }}
        {{- end }}
          volumeMounts:
          - name: logs
            mountPath: /var/log/api-market
      tolerations:
      - key: "api.mkt.nodeType"
        operator: "Equal"
        value: {{ .Values.deployment.container.namespace }}
        effect: "NoSchedule"
      initContainers:
      - name: {{ .Chart.Name }}-init
        securityContext:
          runAsUser: 0
        image: busybox
        command: ["/bin/chmod", "-R", "777", "/var/log/api-market"]
        volumeMounts:
        - name: logs
          mountPath: /var/log/api-market
      volumes:
        - name: logs
          hostPath:
            path: /var/log/api-market
---
##################################################################################################
## Virtual service                                                                          ##
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.deployment.container.namespace }}
spec:
  gateways: 
  - istio-system/main-gateway
  hosts:
  - "*"
  http:
  - match:
{{- $namespace := .Values.deployment.container.namespace -}}
{{- range .Files.Lines "routes.txt" }}
      -
      {{- if regexFind "(dev|qa)" $namespace }}
        headers:
          x-environment:
            exact: {{ $namespace }}
      {{- end }}
        method:
          exact: {{ (split " " .)._1 }}
        uri:
          {{- if regexFind "\\.\\+" (split " " .)._0  }}  
          regex: {{ (split " " .)._0 }}
          {{- else }}
          exact: {{ (split " " .)._0 }}
          {{- end }}
{{- end }}
    route:
      - destination:
          host: {{ .Chart.Name }}
          port: 
            number: 90
    