##################################################################################################
## Storage class encrypted                                                                      ##
##################################################################################################
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: encrypted-gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
parameters:
  type: gp2
  fsType: ext4
  encrypted: "true"