##################################################################################################
# Create serviceAccount
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-namespace: "reloader"
    meta.helm.sh/release-name: "stakater"
  labels:
    app: stakater-reloader
    chart: "reloader-v0.0.99"
    release: "stakater"
    heritage: "Helm"
    app.kubernetes.io/managed-by: "Helm"
  name: stakater-reloader
  namespace: reloader
---
##################################################################################################
# Cluster Role
##################################################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-namespace: "reloader"
    meta.helm.sh/release-name: "stakater"
  labels:
    app: stakater-reloader
    chart: "reloader-v0.0.99"
    release: "stakater"
    heritage: "Helm"
    app.kubernetes.io/managed-by: "Helm"
  name: stakater-reloader-role
  namespace: reloader
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - list
      - get
      - update
      - patch
  - apiGroups:
      - "extensions"
    resources:
      - deployments
      - daemonsets
    verbs:
      - list
      - get
      - update
      - patch
---
##################################################################################################
# ClusterRoleBinding
##################################################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-namespace: "reloader"
    meta.helm.sh/release-name: "stakater"
  labels:
    app: stakater-reloader
    chart: "reloader-v0.0.99"
    release: "stakater"
    heritage: "Helm"
    app.kubernetes.io/managed-by: "Helm"
  name: stakater-reloader-role-binding
  namespace: reloader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stakater-reloader-role
subjects:
  - kind: ServiceAccount
    name: stakater-reloader
    namespace: reloader
---
##################################################################################################
# Deployment
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-namespace: "reloader"
    meta.helm.sh/release-name: "stakater"
  labels:
    app: stakater-reloader
    chart: "reloader-v0.0.99"
    release: "stakater"
    heritage: "Helm"
    app.kubernetes.io/managed-by: "Helm"
    group: com.stakater.platform
    provider: stakater
    version: v0.0.99
  name: stakater-reloader
  namespace: reloader
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: stakater-reloader
      release: "stakater"
  template:
    metadata:
      labels:
        app: stakater-reloader
        chart: "reloader-v0.0.99"
        release: "stakater"
        heritage: "Helm"
        app.kubernetes.io/managed-by: "Helm"
        group: com.stakater.platform
        provider: stakater
        version: v0.0.99
    spec:
      tolerations:
      - key: "api.mkt.nodeType"
        operator: "Equal"
        value: "istio"
        effect: "NoSchedule"
      containers:
      - image: "stakater/reloader:v0.0.99"
        imagePullPolicy: IfNotPresent
        name: stakater-reloader
        resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
        ports:
        - name: http
          containerPort: 9090
        livenessProbe:
          httpGet:
            path: /metrics
            port: http
          timeoutSeconds: 5
          failureThreshold: 5
          periodSeconds: 10
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /metrics
            port: http
          timeoutSeconds: 5
          failureThreshold: 5
          periodSeconds: 10
          successThreshold: 1
      securityContext: 
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: stakater-reloader