##################################################################################################
# Create ns
##################################################################################################
apiVersion: v1
kind: Namespace
metadata:
  name: {{NAMESPACE}}